version: "3.7"

services:

    nginx-proxy:
        image: "nginxproxy/nginx-proxy:latest"
        container_name: "nginx-proxy"
        ports:
            - "${IPv4}:${HTTP_PORT}:80"
            - "${IPv4}:${HTTPS_PORT}:443"
        volumes:
            - "${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d"
            - "${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d:ro"
            - "${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro"
            - "${NGINX_FILES_PATH}/html:/usr/share/nginx/html:ro"
            - "${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro"
            - "${NGINX_FILES_PATH}/dhparam:/etc/nginx/dhparam"
            - "${NGINX_FILES_PATH}/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro"
        restart: "always"
        logging:
            options:
                max-size: '4m'
                max-file: '10'

    nginx-gen:
        image: nginxproxy/docker-gen:latest
        privileged: true
        container_name: nginx-proxy-gen
        command: -notify-sighup nginx-proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - "${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d"
            - "${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d"
            - "${NGINX_FILES_PATH}/html:/usr/share/nginx/html"
            - "${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro"
            - "${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro"
            - "${NGINX_FILES_PATH}/dhparam:/etc/nginx/dhparam"
            - "${DOCKER_GEN_FILES_PATH}/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: "always"
        logging:
            options:
                max-size: '4m'
                max-file: '10'

    acme-companion:
        image: "nginxproxy/acme-companion:latest"
        container_name: "nginx-proxy-acme"
        privileged: true
        volumes:
            - "${NGINX_FILES_PATH}/conf:/etc/nginx/conf.d"
            - "${NGINX_FILES_PATH}/vhost:/etc/nginx/vhost.d"
            - "${NGINX_FILES_PATH}/html:/usr/share/nginx/html"
            - "${NGINX_FILES_PATH}/dhparam:/etc/nginx/dhparam"
            - "${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw"
            - "${ACME_FILES_PATH}/acme:/etc/acme.sh"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_DOCKER_GEN_CONTAINER: "${DOCKER_GEN_SEVICE_NAME}"
            NGINX_PROXY_CONTAINER: "${NGINX_WEB_SEVICE_NAME}"
            DEFAULT_EMAIL: "${DEFAULT_EMAIL}"
            ACME_CA_URI: "${ACME_CA_URI}"
        restart: "always"
        depends_on:
            - "${NGINX_WEB_SEVICE_NAME}"
        logging:
            options:
                max-size: '4m'
                max-file: '10'

networks:
  default:
    external: true
    name: "${NETWORK}"