version: "3"

services:
  app-filebrowser:
    container_name: app-filebrowser
    image: filebrowser/filebrowser
    user: 1000:1000
    networks:
      - nginx-proxy
    ports:
      - "127.0.0.1:8081:80"
    healthcheck:
      test: curl -f http://127.0.0.1:8081/health || exit 1
    volumes:
      - /home:/srv
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
    restart: always
    security_opt:
      - no-new-privileges:true

networks:
  nginx-proxy:
    external: true