version: "3.3"

services:
  nginx-reverse:
    container_name: ${NGINX_WEB_SEVICE_NAME}
    image: nginx:alpine
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${LE_FILES_PATH}/etc/letsencrypt:/etc/letsencrypt:ro
      - ${ACME_FILES_PATH}/tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - ${NETWORK}
    restart: always
    
networks:
  nginx-proxy:
    external: true