version: "3"

services:
  app-firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: app-firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    ports:
      - "0.0.0.0:3000:3000"
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true