version: "3"

services:
  app-portainer:
    container_name: app-portainer
    image: portainer/portainer-ce:latest
    networks:
      - nginx-proxy
    ports:
      - "127.0.0.1:9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always

networks:
  nginx-proxy:
    external: true